### ISSUE TITLE
Releasing package with tags

### ISSUE THREAD

**Issue by butuzov** [julz/importas#10]
@julz is it possible to use [semver](https://semver.org/) based tagging (add tags after adding features or fixing bugs), it can make the life of the maintainers of tools that depend on `importas` way easier (speaking about myself who is trying to keep tooling updated as much as possible in `golangci-lint`).

Also, @dependabot can easily track dependencies, which is also a nice thing to have.

**Comment by julz** [comment]
Sounds reasonable to me @butuzov, done. Thanks!
